CREATE TABLE "intervention" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "intervention_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" varchar(30) NOT NULL,
	"description" text NOT NULL,
	"status" varchar(20) DEFAULT 'programmato' NOT NULL,
	"intervention_date" date,
	"start_time" time,
	"end_time" time,
	"updated_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"customer_id" integer NOT NULL,
	"technician_id" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "intervention" ADD CONSTRAINT "intervention_customer_id_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customer"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "intervention" ADD CONSTRAINT "intervention_technician_id_technician_id_fk" FOREIGN KEY ("technician_id") REFERENCES "public"."technician"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "intervention_customer_id_idx" ON "intervention" USING btree ("customer_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "intervention_technician_id_idx" ON "intervention" USING btree ("technician_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "intervention_type_idx" ON "intervention" USING btree ("type");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "intervention_status_idx" ON "intervention" USING btree ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "intervention_description_trgm_idx" ON "intervention" USING gin ("description" gin_trgm_ops);
