CREATE TABLE "notification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"dedupe_key" varchar(255) NOT NULL,
	"severity" varchar(20) DEFAULT 'info' NOT NULL,
	"title" varchar(255) NOT NULL,
	"message" text,
	"link" varchar(512),
	"occurrences" integer DEFAULT 1 NOT NULL,
	"last_occurred_at" timestamp DEFAULT now() NOT NULL,
	"dismissed_at" timestamp,
	"updated_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "notification_dedupe_key_unique" UNIQUE("dedupe_key")
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "notification_last_occurred_at_idx" ON "notification" USING btree ("last_occurred_at");
